### ISSUE TITLE
Undefined array key 2

### ISSUE THREAD

**Issue by tm1000** [psalm/psalm-vscode-plugin#105]
Issue Type: <b>Bug</b>

# Behaviour

## Expected

XXX

## Actual

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1.

# Diagnostic data

-   PHP version: PHP 8.0.9 (cli) (built: Jul 30 2021 13:04:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.9, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans

-   Psalm version: 4.10.0

<details>

<summary>"Psalm Language Server" channel in the OUTPUT panel (Last 1000 lines)</summary>

<p>

```
[INFO - 6:25:12 AM] Starting language server
[INFO - 6:25:13 AM] Starting Psalm Language Server
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Language server has started.
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Initializing...
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Initializing: Getting code base...
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Initializing: Scanning files...
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Initializing: Registering stub files...
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Initializing: Complete.
[INFO - 6:25:29 AM] The Language Server is ready
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[ERROR - 6:27:56 AM] completion not found at 24:9

completion not found at 24:9

[ERROR - 6:27:57 AM] completion not found at 24:14

completion not found at 24:14

[ERROR - 6:28:30 AM] completion not found at 24:9

completion not found at 24:9

[ERROR - 6:28:30 AM] completion not found at 24:13

completion not found at 24:13

[ERROR - 6:28:31 AM] completion not found at 24:15

completion not found at 24:15

[ERROR - 6:28:31 AM] completion not found at 24:17

completion not found at 24:17

[ERROR - 6:28:40 AM] completion not found at 42:11

completion not found at 42:11

[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/vendor/laravel/framework/src/Illuminate/Collections/Collection.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/pulsar-sms-callbackapi2/src/tests/Feature/MessageTest.php is not in project
[ERROR - 6:35:33 AM] completion not found at 67:17

completion not found at 67:17

[ERROR - 6:35:33 AM] completion not found at 67:21

completion not found at 67:21

[ERROR - 6:36:22 AM] completion not found at 68:24

completion not found at 68:24

[ERROR - 6:36:30 AM] completion not found at 68:31

completion not found at 68:31

[ERROR - 6:36:41 AM] completion not found at 67:20

completion not found at 67:20

[ERROR - 6:36:45 AM] completion not found at 67:25

completion not found at 67:25

[ERROR - 6:36:49 AM] completion not found at 67:32

completion not found at 67:32

[ERROR - 6:36:52 AM] completion not found at 67:31

completion not found at 67:31

[ERROR - 6:37:00 AM] completion not found at 69:38

completion not found at 69:38

[ERROR - 6:37:40 AM] completion not found at 79:5

completion not found at 79:5

[ERROR - 6:37:41 AM] completion not found at 79:11

completion not found at 79:11

[ERROR - 6:37:42 AM] completion not found at 79:12

completion not found at 79:12

[ERROR - 6:37:42 AM] completion not found at 79:18

completion not found at 79:18

[ERROR - 6:37:43 AM] completion not found at 79:19

completion not found at 79:19

[ERROR - 6:37:43 AM] completion not found at 79:27

completion not found at 79:27

[ERROR - 6:37:45 AM] completion not found at 79:31

completion not found at 79:31

[ERROR - 6:37:48 AM] completion not found at 79:44

completion not found at 79:44

[ERROR - 6:38:31 AM] completion not found at 80:43

completion not found at 80:43

[ERROR - 6:38:32 AM] completion not found at 80:49

completion not found at 80:49

[ERROR - 6:38:32 AM] completion not found at 80:50

completion not found at 80:50

[ERROR - 6:38:32 AM] completion not found at 80:53

completion not found at 80:53

[ERROR - 6:38:33 AM] completion not found at 80:58

completion not found at 80:58

[ERROR - 6:38:46 AM] completion not found at 83:15

completion not found at 83:15

[ERROR - 6:38:56 AM] completion not found at 81:11

completion not found at 81:11

[ERROR - 6:38:57 AM] completion not found at 81:17

completion not found at 81:17

[ERROR - 6:38:59 AM] completion not found at 81:16

completion not found at 81:16

[ERROR - 6:38:59 AM] completion not found at 81:21

completion not found at 81:21

[ERROR - 6:39:00 AM] completion not found at 81:26

completion not found at 81:26

[ERROR - 6:39:38 AM] completion not found at 70:21

completion not found at 70:21

[ERROR - 6:39:53 AM] completion not found at 74:40

completion not found at 74:40

[ERROR - 6:40:16 AM] completion not found at 54:24

completion not found at 54:24

[ERROR - 6:40:22 AM] completion not found at 74:40

completion not found at 74:40

[ERROR - 6:42:22 AM] completion not found at 62:11

completion not found at 62:11

[ERROR - 6:42:23 AM] completion not found at 62:17

completion not found at 62:17

[ERROR - 6:42:24 AM] completion not found at 62:21

completion not found at 62:21

[ERROR - 6:42:26 AM] completion not found at 62:28

completion not found at 62:28

[ERROR - 6:42:50 AM] Expecting non-empty $root_file_path and $checked_file_path

Expecting non-empty $root_file_path and $checked_file_path

[ERROR - 6:42:59 AM] completion not found at 65:33

completion not found at 65:33

[ERROR - 6:43:02 AM] completion not found at 65:36

completion not found at 65:36

[Error - 6:43:07 AM] Request textDocument/completion failed.
  Message: ErrorException: Undefined array key 2 in /usr/src/pulsar-sms-callbackapi2/src/vendor/vimeo/psalm/src/Psalm/Codebase.php:1480
Stack trace:
#0 /usr/src/pulsar-sms-callbackapi2/src/vendor/vimeo/psalm/src/Psalm/Codebase.php(1480): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /usr/src/pulsar-sms-callbackapi2/src/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(274): Psalm\Codebase->getTypeContextAtPosition()
#2 /usr/src/pulsar-sms-callbackapi2/src/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(168): Psalm\Internal\LanguageServer\Server\TextDocument->completion()
#3 /usr/src/pulsar-sms-callbackapi2/src/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(140): AdvancedJsonRpc\Dispatcher->dispatch()
#4 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#5 /usr/src/pulsar-sms-callbackapi2/src/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#6 /usr/src/pulsar-sms-callbackapi2/src/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#7 /usr/src/pulsar-sms-callbackapi2/src/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#8 /usr/src/pulsar-sms-callbackapi2/src/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(78): Amp\{closure}()
#9 /usr/src/pulsar-sms-callbackapi2/src/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(118): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#10 /usr/src/pulsar-sms-callbackapi2/src/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(67): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages()
#11 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#12 /usr/src/pulsar-sms-callbackapi2/src/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#13 /usr/src/pulsar-sms-callbackapi2/src/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#14 /usr/src/pulsar-sms-callbackapi2/src/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#15 /usr/src/pulsar-sms-callbackapi2/src/vendor/amphp/byte-stream/lib/ResourceInputStream.php(109): Amp\Deferred->resolve()
#16 /usr/src/pulsar-sms-callbackapi2/src/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#17 /usr/src/pulsar-sms-callbackapi2/src/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#18 /usr/src/pulsar-sms-callbackapi2/src/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#19 /usr/src/pulsar-sms-callbackapi2/src/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(533): Amp\Loop::run()
#20 /usr/src/pulsar-sms-callbackapi2/src/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(312): Psalm\Internal\Analyzer\ProjectAnalyzer->server()
#21 /usr/src/pulsar-sms-callbackapi2/src/vendor/vimeo/psalm/psalm-language-server(4): Psalm\Internal\Cli\LanguageServer::run()
#22 {main}
  Code: -32603 
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
phpExecutablePath: "/usr/bin/php"
phpExecutableArgs: ["-dxdebug.remote_autostart=0","-dxdebug.remote_enable=0","-dxdebug_profiler_enable=0"]
psalmScriptPath: "src/vendor/bin/psalm-language-server"
maxRestartCount: 5
unusedVariableDetection: false
enableVerbose: true
connectToServerWithTcp: false
enableUseIniDefaults: false
logLevel: "INFO"
analyzedFileExtensions: [{"scheme":"file","language":"php"},{"scheme":"untitled","language":"php"}]
configPaths: ["src/psalm.xml"]
hideStatusMessageWhenRunning: true
```

</p>
</details>

Extension version: 2.3.0
VS Code version: Code 1.60.1 (Universal) (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No
Remote OS version: Linux x64 5.11.0-34-generic

**Comment by tm1000** [comment]
Fixed in https://github.com/vimeo/psalm/issues/6559
