### ISSUE TITLE
UnexpectedValueException: Expecting non-empty $root_file_path and $checked_file_path

### ISSUE THREAD

**Issue by tm1000** [psalm/psalm-vscode-plugin#107]
Issue Type: <b>Bug</b>

# Behaviour

## Expected

XXX

## Actual

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1.

# Diagnostic data

-   PHP version: PHP 8.0.9 (cli) (built: Jul 30 2021 13:04:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.9, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans

-   Psalm version: 4.10.0

<details>

<summary>"Psalm Language Server" channel in the OUTPUT panel (Last 1000 lines)</summary>

<p>

```
[INFO - 7:35:32 PM] Starting language server
[INFO - 7:35:33 PM] Starting Psalm Language Server
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Language server has started.
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Initializing...
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Initializing: Getting code base...
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Initializing: Scanning files...
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Initializing: Registering stub files...
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] Initializing: Complete.
[INFO - 7:35:55 PM] The Language Server is ready
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/project/vendor/project/telephony/src/Client.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/project/vendor/project/telephony/src/Client.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/project/vendor/project/telephony/src/Client.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/project/vendor/project/telephony/src/Client.php is not in project
[Psalm 4.10.0@916b098b008f6de4543892b1e0651c1c3b92cbfa - PHP Language Server] /usr/src/project/vendor/project/telephony/src/Client.php is not in project
[Error - 8:05:05 PM] Request textDocument/completion failed.
  Message: UnexpectedValueException: Expecting non-empty $root_file_path and $checked_file_path in /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php:111
Stack trace:
#0 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Codebase.php(962): Psalm\Internal\Codebase\Functions->getStorage()
#1 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Codebase.php(1476): Psalm\Codebase->getFunctionStorageForSymbol()
#2 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(274): Psalm\Codebase->getTypeContextAtPosition()
#3 /usr/src/project/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(168): Psalm\Internal\LanguageServer\Server\TextDocument->completion()
#4 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(140): AdvancedJsonRpc\Dispatcher->dispatch()
#5 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#6 /usr/src/project/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#7 /usr/src/project/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#8 /usr/src/project/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#9 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(78): Amp\{closure}()
#10 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(118): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#11 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(67): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages()
#12 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#13 /usr/src/project/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#14 /usr/src/project/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#15 /usr/src/project/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#16 /usr/src/project/vendor/amphp/byte-stream/lib/ResourceInputStream.php(109): Amp\Deferred->resolve()
#17 /usr/src/project/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#18 /usr/src/project/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#19 /usr/src/project/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#20 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(533): Amp\Loop::run()
#21 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(312): Psalm\Internal\Analyzer\ProjectAnalyzer->server()
#22 /usr/src/project/vendor/vimeo/psalm/psalm-language-server(4): Psalm\Internal\Cli\LanguageServer::run()
#23 {main}
  Code: -32603 
[Error - 8:05:05 PM] Request textDocument/completion failed.
  Message: UnexpectedValueException: Expecting non-empty $root_file_path and $checked_file_path in /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php:111
Stack trace:
#0 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Codebase.php(962): Psalm\Internal\Codebase\Functions->getStorage()
#1 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Codebase.php(1476): Psalm\Codebase->getFunctionStorageForSymbol()
#2 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(274): Psalm\Codebase->getTypeContextAtPosition()
#3 /usr/src/project/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(168): Psalm\Internal\LanguageServer\Server\TextDocument->completion()
#4 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(140): AdvancedJsonRpc\Dispatcher->dispatch()
#5 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#6 /usr/src/project/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#7 /usr/src/project/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#8 /usr/src/project/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#9 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(78): Amp\{closure}()
#10 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(118): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#11 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(67): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages()
#12 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#13 /usr/src/project/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#14 /usr/src/project/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#15 /usr/src/project/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#16 /usr/src/project/vendor/amphp/byte-stream/lib/ResourceInputStream.php(109): Amp\Deferred->resolve()
#17 /usr/src/project/vendor/amphp/amp/lib/Loop/Driver.php(119): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#18 /usr/src/project/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#19 /usr/src/project/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#20 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(533): Amp\Loop::run()
#21 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(312): Psalm\Internal\Analyzer\ProjectAnalyzer->server()
#22 /usr/src/project/vendor/vimeo/psalm/psalm-language-server(4): Psalm\Internal\Cli\LanguageServer::run()
#23 {main}
  Code: -32603 
[Error - 8:05:06 PM] Request textDocument/completion failed.
  Message: UnexpectedValueException: Expecting non-empty $root_file_path and $checked_file_path in /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Functions.php:111
Stack trace:
#0 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Codebase.php(962): Psalm\Internal\Codebase\Functions->getStorage()
#1 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Codebase.php(1476): Psalm\Codebase->getFunctionStorageForSymbol()
#2 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(274): Psalm\Codebase->getTypeContextAtPosition()
#3 /usr/src/project/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(168): Psalm\Internal\LanguageServer\Server\TextDocument->completion()
#4 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(140): AdvancedJsonRpc\Dispatcher->dispatch()
#5 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#6 /usr/src/project/vendor/amphp/amp/lib/Coroutine.php(67): Generator->current()
#7 /usr/src/project/vendor/amphp/amp/lib/functions.php(96): Amp\Coroutine->__construct()
#8 /usr/src/project/vendor/amphp/amp/lib/functions.php(61): Amp\call()
#9 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(78): Amp\{closure}()
#10 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(118): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#11 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(67): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages()
#12 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#13 /usr/src/project/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#14 /usr/src/project/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#15 /usr/src/project/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#16 /usr/src/project/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#17 /usr/src/project/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#18 /usr/src/project/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams()
#19 /usr/src/project/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#20 /usr/src/project/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#21 /usr/src/project/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#22 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(533): Amp\Loop::run()
#23 /usr/src/project/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(312): Psalm\Internal\Analyzer\ProjectAnalyzer->server()
#24 /usr/src/project/vendor/vimeo/psalm/psalm-language-server(4): Psalm\Internal\Cli\LanguageServer::run()
#25 {main}
  Code: -32603 
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
phpExecutablePath: "/usr/bin/php"
phpExecutableArgs: ["-dxdebug.remote_autostart=0","-dxdebug.remote_enable=0","-dxdebug_profiler_enable=0"]
psalmScriptPath: "app/vendor/bin/psalm-language-server"
maxRestartCount: 5
unusedVariableDetection: false
enableVerbose: true
connectToServerWithTcp: false
enableUseIniDefaults: false
logLevel: "INFO"
analyzedFileExtensions: [{"scheme":"file","language":"php"},{"scheme":"untitled","language":"php"}]
configPaths: ["app/psalm.xml"]
hideStatusMessageWhenRunning: true
```

</p>
</details>

Extension version: 2.3.0
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.11.0-34-generic
Remote OS version: Linux x64 5.11.0-34-generic
Remote OS version: Linux x64 5.11.0-34-generic

**Comment by tm1000** [comment]
Fixed in 4.17.0
