### ISSUE TITLE
Broken pipe error

### ISSUE THREAD

**Issue by palansher** [psalm/psalm-vscode-plugin#148]
Hello! thank you for your work!

Do you have any idea why this amphp (psalm dependency) error is rising almost after every code change?

All trace attached.
 
VSCODE 1.6.2  + ssh remote
Windows 10 x64 

```
#4. unknown(0):fwrite
#5. /home/vladp/dev/sites/gt-vladp-dev1/vendor/amphp/byte-stream/lib/ResourceOutputStream.php(204):send
#6. /home/vladp/dev/sites/gt-vladp-dev1/vendor/amphp/byte-stream/lib/ResourceOutputStream.php(157):write
#7. /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamWriter.php(33):write
#8. /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ClientHandler.php(107):notify
#9. /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageClient.php(60):logMessage
#10. /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(502):clientStatus
#11. /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(439):shutdown
#12. /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(120):Psalm\Internal\LanguageServer\{closure}
#13. /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(84):emit
#14. /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(146):emitClose
#15. /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(72):Psalm\Internal\LanguageServer\{closure}
#16. unknown(0):send

```
[errors.log](https://github.com/psalm/psalm-vscode-plugin/files/7954949/errors.log)

**Comment by tm1000** [comment]
For windows you should enable TCP mode (it's in settings)

**Comment by palansher** [comment]
thank you!

I did it 
![image](https://user-images.githubusercontent.com/24850253/151470872-0f6d8aa7-91e0-45d8-957f-10edd400de2a.png)

Unfortunately during code changing now I have a little different error:

![image](https://user-images.githubusercontent.com/24850253/151471272-25c8623c-28d5-4c14-9c00-adfaf5a902aa.png)

Which "main repository" you have mentioned?

```
[2022-01-28T04:28:21.606442+03:00] CommonErrors.ERROR: fatal:1 Exception (0) Could not get class storage for gt\settingsinterface  on line 46 in /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php
#0 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassLikeAnalyzer.php(109): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/InterfaceAnalyzer.php(26): Psalm\Internal\Analyzer\ClassLikeAnalyzer->__construct()
#2 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/NamespaceAnalyzer.php(117): Psalm\Internal\Analyzer\InterfaceAnalyzer->__construct()
#3 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/NamespaceAnalyzer.php(70): Psalm\Internal\Analyzer\NamespaceAnalyzer->collectAnalyzableClassLike()
#4 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(314): Psalm\Internal\Analyzer\NamespaceAnalyzer->collectAnalyzableInformation()
#5 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(193): Psalm\Internal\Analyzer\FileAnalyzer->populateCheckers()
#6 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(362): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#7 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(619): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#8 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(291): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#9 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(349): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#10 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(188): Psalm\Internal\LanguageServer\LanguageServer->doAnalysis()
#11 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(84): Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}()
#12 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(68): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit()
#13 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#14 /home/vladp/dev/sites/gt-vladp-dev1/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send()
#15 /home/vladp/dev/sites/gt-vladp-dev1/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}()
#16 /home/vladp/dev/sites/gt-vladp-dev1/vendor/amphp/amp/lib/Deferred.php(53): Amp\Promise@anonymous->resolve()
#17 /home/vladp/dev/sites/gt-vladp-dev1/vendor/amphp/byte-stream/lib/ResourceInputStream.php(101): Amp\Deferred->resolve()
#18 /home/vladp/dev/sites/gt-vladp-dev1/vendor/amphp/amp/lib/Loop/NativeDriver.php(327): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}()
#19 /home/vladp/dev/sites/gt-vladp-dev1/vendor/amphp/amp/lib/Loop/NativeDriver.php(127): Amp\Loop\NativeDriver->selectStreams()
#20 /home/vladp/dev/sites/gt-vladp-dev1/vendor/amphp/amp/lib/Loop/Driver.php(138): Amp\Loop\NativeDriver->dispatch()
#21 /home/vladp/dev/sites/gt-vladp-dev1/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#22 /home/vladp/dev/sites/gt-vladp-dev1/vendor/amphp/amp/lib/Loop.php(95): Amp\Loop\Driver->run()
#23 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(480): Amp\Loop::run()
#24 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Cli/LanguageServer.php(321): Psalm\Internal\Analyzer\ProjectAnalyzer->server()
#25 /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/psalm-language-server(7): Psalm\Internal\Cli\LanguageServer::run()
#26 {main}  

```

**Comment by palansher** [comment]
in output also:

  Code: -32603 
[Info  - 4:47:23 AM] Connection to server got closed. Server will restart.
[Error - 4:47:42 AM] Request textDocument/codeAction failed.
  Message: InvalidArgumentException: Could not get file storage for /home/vladp/dev/sites/gt-vladp-dev1/src/paymenttodriver/settings/settingsinterface.php in /home/vladp/dev/sites/gt-vladp-dev1/vendor/vimeo/psalm/src/Psalm/Internal/Provider/FileStorageProvider.php:47

**Comment by tm1000** [comment]
There seems to be something wrong with your system. You have no storage. 

Anyways the code base your are looking for is Vimeo/psalm. There is no php code here.

**Comment by tm1000** [comment]
https://github.com/vimeo/psalm

**Comment by tm1000** [comment]
These errors are already fixed upstream 

https://github.com/vimeo/psalm/pull/7384

The last release was 19 days ago. So you'll have to wait for another release

**Comment by orklah** [comment]
4.19.0 has been released

**Comment by palansher** [comment]
Now is much much better! Such a relief !! Thank you for the tips!
