### ISSUE TITLE
Request textDocument/definition failed.

### ISSUE THREAD

**Issue by JaPawel** [psalm/psalm-vscode-plugin#4]
Not sure is it the extension or `vimeo/psalm` lib, but I get from time to time `Request textDocument/definition failed.` errors (only in VSCode when extension is enabled, never when called psalm directly via command line)

```
[Error - 02:16:46] Request textDocument/definition failed.
  Message: InvalidArgumentException: Could not get class storage for type: bool in /Users/__USER__/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:43
Stack trace:
#0 /Users/__USER__/.composer/vendor/vimeo/psalm/src/Psalm/Codebase.php(1021): Psalm\Internal\Provider\ClassLikeStorageProvider->get('type: bool')
#1 /Users/__USER__/.composer/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/Server/TextDocument.php(183): Psalm\Codebase->getSymbolLocation('/Users/__USER__...', 'type: bool')
#2 /Users/__USER__/.composer/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(160): Psalm\Internal\LanguageServer\Server\TextDocument->definition(Object(LanguageServerProtocol\TextDocumentIdentifier), Object(LanguageServerProtocol\Position))
#3 /Users/__USER__/.composer/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/LanguageServer.php(116): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#4 [internal function]: Psalm\Internal\LanguageServer\LanguageServer->Psalm\Internal\LanguageServer\{closure}(Object(Psalm\Internal\LanguageServer\Message))
#5 /Users/__USER__/.composer/vendor/amphp/amp/lib/Coroutine.php(41): Generator->current()
#6 /Users/__USER__/Projects/Web/ContactsSyncer/vendor/amphp/amp/lib/functions.php(66): Amp\Coroutine->__construct(Object(Generator))
#7 /Users/__USER__/Projects/Web/ContactsSyncer/vendor/amphp/amp/lib/functions.php(44): Amp\call(Object(Closure), Object(Psalm\Internal\LanguageServer\Message))
#8 /Users/__USER__/.composer/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/EmitterTrait.php(78): Amp\{closure}(Object(Psalm\Internal\LanguageServer\Message))
#9 /Users/__USER__/.composer/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(107): Psalm\Internal\LanguageServer\ProtocolStreamReader->emit('message', Array)
#10 /Users/__USER__/.composer/vendor/vimeo/psalm/src/Psalm/Internal/LanguageServer/ProtocolStreamReader.php(51): Psalm\Internal\LanguageServer\ProtocolStreamReader->readMessages('Content-Length:...')
#11 [internal function]: Psalm\Internal\LanguageServer\ProtocolStreamReader->Psalm\Internal\LanguageServer\{closure}()
#12 /Users/__USER__/.composer/vendor/amphp/amp/lib/Coroutine.php(76): Generator->send('Content-Length:...')
#13 /Users/__USER__/.composer/vendor/amphp/amp/lib/Internal/Placeholder.php(130): Amp\Coroutine->Amp\{closure}(NULL, 'Content-Length:...')
#14 /Users/__USER__/.composer/vendor/amphp/amp/lib/Deferred.php(45): class@anonymous->resolve('Content-Length:...')
#15 /Users/__USER__/.composer/vendor/amphp/byte-stream/lib/ResourceInputStream.php(99): Amp\Deferred->resolve('Content-Length:...')
#16 /Users/__USER__/.composer/vendor/amphp/amp/lib/Loop/NativeDriver.php(206): Amp\ByteStream\ResourceInputStream::Amp\ByteStream\{closure}('a', Resource id #1, NULL)
#17 /Users/__USER__/.composer/vendor/amphp/amp/lib/Loop/NativeDriver.php(97): Amp\Loop\NativeDriver->selectStreams(Array, Array, -0.001)
#18 /Users/__USER__/.composer/vendor/amphp/amp/lib/Loop/Driver.php(134): Amp\Loop\NativeDriver->dispatch(true)
#19 /Users/__USER__/.composer/vendor/amphp/amp/lib/Loop/Driver.php(72): Amp\Loop\Driver->tick()
#20 /Users/__USER__/.composer/vendor/amphp/amp/lib/Loop.php(84): Amp\Loop\Driver->run()
#21 /Users/__USER__/.composer/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(309): Amp\Loop::run()
#22 /Users/__USER__/.composer/vendor/vimeo/psalm/src/psalm-language-server.php(240): Psalm\Internal\Analyzer\ProjectAnalyzer->server(NULL, false)
#23 /Users/__USER__/.composer/vendor/vimeo/psalm/psalm-language-server(2): require_once('/Users/__USER__...')
#24 {main}
  Code: -32603 
```

This one is for `bool`, but for others I get errors too.

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/a34692fca0ce54be05a5d7ffbff8ee8bfd4867dd
