### ISSUE TITLE
Go to definition gives "Cannot read property 'kind' of null"

### ISSUE THREAD

**Issue by thbley2** [psalm/psalm-vscode-plugin#82]
When I try to go to the definition of a method, it's sometimes not working without an error message and sometimes I get:

ERR Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at b (/config/.local/share/code-server/extensions/getpsalm.psalm-vscode-plugin-2.1.0/dist/extension.js:1:193027)
	at k (/config/.local/share/code-server/extensions/getpsalm.psalm-vscode-plugin-2.1.0/dist/extension.js:1:195311)
	at Array.map (<anonymous>)
	at O (/config/.local/share/code-server/extensions/getpsalm.psalm-vscode-plugin-2.1.0/dist/extension.js:1:195198)
	at asSignatureHelp (/config/.local/share/code-server/extensions/getpsalm.psalm-vscode-plugin-2.1.0/dist/extension.js:1:201748)

Psalm 4.9.3, code-server 3.11.1, getpsalm.psalm-vscode-plugin v2.1.0

**Comment by tm1000** [comment]
Looks like I'll need to figure out how to get JavaScript maps to work to be able to track this down correctly

**Comment by thomasbley** [comment]
The code I tested with does not use __invoke().

**Comment by tm1000** [comment]
Can you provide an example?
